name: New Feature
description: Suggest a new feature for ScratchTools, or an enhancement for a feature.
labels: ["new feature"]
body:

  - type: textarea
    id: describe
    attributes:
      label: How does the feature work?
      description: Describe what you're suggesting.
      placeholder: Type here
    validations:
      required: true
  
  - type: textarea
    id: why
    attributes:
      label: What situations would make this helpful?
      description: Who would find this helpful, and when?
      placeholder: Type here
    validations:
      required: true

  - type: textarea
    id: extra
    attributes:
      label: Anything else?
      description: You can put more info here if you have any.
